fix: don't call abort if it's not a function
When calling rendering-grid-client's `makeEyesOpen` with
`isDisabled=true`, an object will be returned that has no `abort`
property. This code will still try to call `abort()` causing the
following error: "abort is not a function"